export const imagesDay = {
  Sunny: "src/assets/weather_svg_img/weather_clearDay.svg",
  Clear: "src/assets/weather_svg_img/weather_clearDay.svg",
  "Partly cloudy": "src/assets/weather_svg_img/weather_partlyCloudyDay.svg",
  Cloudy: "src/assets/weather_svg_img/weather_cloudy.svg",
  Overcast: "src/assets/weather_svg_img/weather_overcast.svg",
  Mist: "src/assets/weather_svg_img/weather_mist.svg",
  "Patchy rain possible": "src/assets/weather_svg_img/weather_patchyRainDay.svg",
  "Patchy snow possible": "src/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Patchy sleet possible": "src/assets/weather_svg_img/weather_patchySleetDay.svg",
  "Patchy freezing drizzle possible": "src/assets/weather_svg_img/weather_fog.svg",
  "Thundery outbreaks possible": "src/assets/weather_svg_img/weather_thunderyOutbreaksDay.svg",
  "Blowing snow": "src/assets/weather_svg_img/weather_blizzard.svg",
  Blizzard: "src/assets/weather_svg_img/weather_blizzard.svg",
  Fog: "src/assets/weather_svg_img/weather_fog.svg",
  "Freezing fog": "src/assets/weather_svg_img/weather_fog.svg",
  "Patchy light drizzle": "src/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Light drizzle": "src/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Freezing drizzle": "src/assets/weather_svg_img/weather_fog.svg",
  "Heavy freezing drizzle": "src/assets/weather_svg_img/weather_fog.svg",
  "Patchy light rain": "src/assets/weather_svg_img/weather_lightRain.svg",
  "Light rain": "src/assets/weather_svg_img/weather_lightRain.svg",
  "Moderate rain at times": "src/assets/weather_svg_img/weather_moderateRainDay.svg",
  "Moderate rain": "src/assets/weather_svg_img/weather_lightRain.svg",
  "Heavy rain at times": "src/assets/weather_svg_img/weather_heavyRainDay.svg",
  "Heavy rain": "src/assets/weather_svg_img/weather_heavyRain.svg",
  "Light freezing rain": "src/assets/weather_svg_img/weather_fog.svg",
  "Moderate or heavy freezing rain": "src/assets/weather_svg_img/weather_fog.svg",
  "Light sleet": "src/assets/weather_svg_img/weather_lightSleet.svg",
  "Moderate or heavy sleet": "src/assets/weather_svg_img/weather_lightSleet.svg",
  "Patchy light snow": "src/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Light snow": "src/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy moderate snow": "src/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Moderate snow": "src/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy heavy snow": "src/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Heavy snow": "src/assets/weather_svg_img/weather_heavySnow.svg",
  "Ice pellets": "src/assets/weather_svg_img/weather_icePellets.svg",
  "Light rain shower": "src/assets/weather_svg_img/weather_patchyRainDay.svg",
  "Moderate or heavy rain shower": "src/assets/weather_svg_img/weather_moderateRainDay.svg",
  "Torrential rain shower": "src/assets/weather_svg_img/weather_torrentialRainDay.svg",
  "Light sleet showers": "src/assets/weather_svg_img/weather_patchySleetDay.svg",
  "Moderate or heavy sleet showers": "src/assets/weather_svg_img/weather_moderateSleetDay.svg",
  "Light snow showers": "src/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Moderate or heavy snow showers": "src/assets/weather_svg_img/weather_moderateSnowDay.svg",
  "Light showers of ice pellets": "src/assets/weather_svg_img/weather_lightIcePelletsDay.svg",
  "Moderate or heavy showers of ice pellets": "src/assets/weather_svg_img/weather_moderateIcePelletsDay.svg",
  "Patchy light rain with thunder": "src/assets/weather_svg_img/weather_thunderyOutbreaksDay.svg",
  "Moderate or heavy rain with thunder": "src/assets/weather_svg_img/weather_moderateThunder.svg",
  "Patchy light snow with thunder": "src/assets/weather_svg_img/weather_patchyThunderSnowDay.svg",
  "Moderate or heavy snow with thunder": "src/assets/weather_svg_img/weather_patchyThunderSnow.svg",
} as { [key: string]: string };

export const imagesNight = {
  Sunny: "src/assets/weather_svg_img/weather_clearNight.svg",
  Clear: "src/assets/weather_svg_img/weather_clearNight.svg",
  "Partly cloudy": "src/assets/weather_svg_img/weather_partlyCloudyNight.svg",
  Cloudy: "src/assets/weather_svg_img/weather_cloudy.svg",
  Overcast: "src/assets/weather_svg_img/weather_overcast.svg",
  Mist: "src/assets/weather_svg_img/weather_mist.svg",
  "Patchy rain possible": "src/assets/weather_svg_img/weather_patchyRainNight.svg",
  "Patchy snow possible": "src/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Patchy sleet possible": "src/assets/weather_svg_img/weather_patchySleetNight.svg",
  "Patchy freezing drizzle possible": "src/assets/weather_svg_img/weather_fog.svg",
  "Thundery outbreaks possible": "src/assets/weather_svg_img/weather_thunderyOutbreaksNight.svg",
  "Blowing snow": "src/assets/weather_svg_img/weather_blizzard.svg",
  Blizzard: "src/assets/weather_svg_img/weather_blizzard.svg",
  Fog: "src/assets/weather_svg_img/weather_fog.svg",
  "Freezing fog": "src/assets/weather_svg_img/weather_fog.svg",
  "Patchy light drizzle": "src/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Light drizzle": "src/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Freezing drizzle": "src/assets/weather_svg_img/weather_fog.svg",
  "Heavy freezing drizzle": "src/assets/weather_svg_img/weather_fog.svg",
  "Patchy light rain": "src/assets/weather_svg_img/weather_lightRain.svg",
  "Light rain": "src/assets/weather_svg_img/weather_lightRain.svg",
  "Moderate rain at times": "src/assets/weather_svg_img/weather_moderateRainNight.svg",
  "Moderate rain": "src/assets/weather_svg_img/weather_lightRain.svg",
  "Heavy rain at times": "src/assets/weather_svg_img/weather_heavyRainNight.svg",
  "Heavy rain": "src/assets/weather_svg_img/weather_heavyRain.svg",
  "Light freezing rain": "src/assets/weather_svg_img/weather_fog.svg",
  "Moderate or heavy freezing rain": "src/assets/weather_svg_img/weather_fog.svg",
  "Light sleet": "src/assets/weather_svg_img/weather_lightSleet.svg",
  "Moderate or heavy sleet": "src/assets/weather_svg_img/weather_lightSleet.svg",
  "Patchy light snow": "src/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Light snow": "src/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy moderate snow": "src/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Moderate snow": "src/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy heavy snow": "src/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Heavy snow": "src/assets/weather_svg_img/weather_heavySnow.svg",
  "Ice pellets": "src/assets/weather_svg_img/weather_icePellets.svg",
  "Light rain shower": "src/assets/weather_svg_img/weather_patchyRainNight.svg",
  "Moderate or heavy rain shower": "src/assets/weather_svg_img/weather_moderateRainNight.svg",
  "Torrential rain shower": "src/assets/weather_svg_img/weather_torrentialRainNight.svg",
  "Light sleet showers": "src/assets/weather_svg_img/weather_patchySleetNight.svg",
  "Moderate or heavy sleet showers": "src/assets/weather_svg_img/weather_moderateSleetNight.svg",
  "Light snow showers": "src/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Moderate or heavy snow showers": "src/assets/weather_svg_img/weather_moderateSnowNight.svg",
  "Light showers of ice pellets": "src/assets/weather_svg_img/weather_lightIcePelletsNight.svg",
  "Moderate or heavy showers of ice pellets": "src/assets/weather_svg_img/weather_moderateIcePelletsNight.svg",
  "Patchy light rain with thunder": "src/assets/weather_svg_img/weather_thunderyOutbreaksNight.svg",
  "Moderate or heavy rain with thunder": "src/assets/weather_svg_img/weather_moderateThunder.svg",
  "Patchy light snow with thunder": "src/assets/weather_svg_img/weather_patchyThunderSnowNight.svg",
  "Moderate or heavy snow with thunder": "src/assets/weather_svg_img/weather_patchyThunderSnow.svg",
} as { [key: string]: string };

export const imagesBgDay = {
  Sunny: "src/assets/weather_webp_img/clearDay.webp",
  Clear: "src/assets/weather_webp_img/clearDay.webp",
  "Partly cloudy": "src/assets/weather_webp_img/partlyCloudyDay.webp",
  Cloudy: "src/assets/weather_webp_img/cloudy.webp",
  Overcast: "src/assets/weather_webp_img/overcast.webp",
  Mist: "src/assets/weather_webp_img/mist.webp",
  "Patchy rain possible": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy snow possible": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy sleet possible": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy freezing drizzle possible": "src/assets/weather_webp_img/mist.webp",
  "Thundery outbreaks possible": "src/assets/weather_webp_img/overcast.webp",
  "Blowing snow": "src/assets/weather_webp_img/overcast.webp",
  Blizzard: "src/assets/weather_webp_img/overcast.webp",
  Fog: "src/assets/weather_webp_img/mist.webp",
  "Freezing fog": "src/assets/weather_webp_img/mist.webp",
  "Patchy light drizzle": "src/assets/weather_webp_img/rain.webp",
  "Light drizzle": "src/assets/weather_webp_img/rain.webp",
  "Freezing drizzle": "src/assets/weather_webp_img/mist.webp",
  "Heavy freezing drizzle": "src/assets/weather_webp_img/mist.webp",
  "Patchy light rain": "src/assets/weather_webp_img/rain.webp",
  "Light rain": "src/assets/weather_webp_img/rain.webp",
  "Moderate rain at times": "src/assets/weather_webp_img/rain.webp",
  "Moderate rain": "src/assets/weather_webp_img/rain.webp",
  "Heavy rain at times": "src/assets/weather_webp_img/rain.webp",
  "Heavy rain": "src/assets/weather_webp_img/rain.webp",
  "Light freezing rain": "src/assets/weather_webp_img/mist.webp",
  "Moderate or heavy freezing rain": "src/assets/weather_webp_img/mist.webp",
  "Light sleet": "src/assets/weather_webp_img/rain.webp",
  "Moderate or heavy sleet": "src/assets/weather_webp_img/rain.webp",
  "Patchy light snow": "src/assets/weather_webp_img/cloudy.webp",
  "Light snow": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy moderate snow": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate snow": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy heavy snow": "src/assets/weather_webp_img/cloudy.webp",
  "Heavy snow": "src/assets/weather_webp_img/cloudy.webp",
  "Ice pellets": "src/assets/weather_webp_img/cloudy.webp",
  "Light rain shower": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy rain shower": "src/assets/weather_webp_img/rain.webp",
  "Torrential rain shower": "src/assets/weather_webp_img/rain.webp",
  "Light sleet showers": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy sleet showers": "src/assets/weather_webp_img/rain.webp",
  "Light snow showers": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy snow showers": "src/assets/weather_webp_img/cloudy.webp",
  "Light showers of ice pellets": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy showers of ice pellets": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy light rain with thunder": "src/assets/weather_webp_img/rain.webp",
  "Moderate or heavy rain with thunder": "src/assets/weather_webp_img/rain.webp",
  "Patchy light snow with thunder": "src/assets/weather_webp_img/rain.webp",
  "Moderate or heavy snow with thunder": "src/assets/weather_webp_img/rain.webp",
} as { [key: string]: string };

export const imagesBgNight = {
  Sunny: "src/assets/weather_webp_img/clearNight.webp",
  Clear: "src/assets/weather_webp_img/clearNight.webp",
  "Partly cloudy": "src/assets/weather_webp_img/partlyCloudyNight.webp",
  Cloudy: "src/assets/weather_webp_img/cloudy.webp",
  Overcast: "src/assets/weather_webp_img/overcast.webp",
  Mist: "src/assets/weather_webp_img/mist.webp",
  "Patchy rain possible": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy snow possible": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy sleet possible": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy freezing drizzle possible": "src/assets/weather_webp_img/mist.webp",
  "Thundery outbreaks possible": "src/assets/weather_webp_img/overcast.webp",
  "Blowing snow": "src/assets/weather_webp_img/overcast.webp",
  Blizzard: "src/assets/weather_webp_img/overcast.webp",
  Fog: "src/assets/weather_webp_img/mist.webp",
  "Freezing fog": "src/assets/weather_webp_img/mist.webp",
  "Patchy light drizzle": "src/assets/weather_webp_img/rain.webp",
  "Light drizzle": "src/assets/weather_webp_img/rain.webp",
  "Freezing drizzle": "src/assets/weather_webp_img/mist.webp",
  "Heavy freezing drizzle": "src/assets/weather_webp_img/mist.webp",
  "Patchy light rain": "src/assets/weather_webp_img/rain.webp",
  "Light rain": "src/assets/weather_webp_img/rain.webp",
  "Moderate rain at times": "src/assets/weather_webp_img/rain.webp",
  "Moderate rain": "src/assets/weather_webp_img/rain.webp",
  "Heavy rain at times": "src/assets/weather_webp_img/rain.webp",
  "Heavy rain": "src/assets/weather_webp_img/rain.webp",
  "Light freezing rain": "src/assets/weather_webp_img/mist.webp",
  "Moderate or heavy freezing rain": "src/assets/weather_webp_img/mist.webp",
  "Light sleet": "src/assets/weather_webp_img/rain.webp",
  "Moderate or heavy sleet": "src/assets/weather_webp_img/rain.webp",
  "Patchy light snow": "src/assets/weather_webp_img/cloudy.webp",
  "Light snow": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy moderate snow": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate snow": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy heavy snow": "src/assets/weather_webp_img/cloudy.webp",
  "Heavy snow": "src/assets/weather_webp_img/cloudy.webp",
  "Ice pellets": "src/assets/weather_webp_img/cloudy.webp",
  "Light rain shower": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy rain shower": "src/assets/weather_webp_img/rain.webp",
  "Torrential rain shower": "src/assets/weather_webp_img/rain.webp",
  "Light sleet showers": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy sleet showers": "src/assets/weather_webp_img/rain.webp",
  "Light snow showers": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy snow showers": "src/assets/weather_webp_img/cloudy.webp",
  "Light showers of ice pellets": "src/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy showers of ice pellets": "src/assets/weather_webp_img/cloudy.webp",
  "Patchy light rain with thunder": "src/assets/weather_webp_img/rain.webp",
  "Moderate or heavy rain with thunder": "src/assets/weather_webp_img/rain.webp",
  "Patchy light snow with thunder": "src/assets/weather_webp_img/rain.webp",
  "Moderate or heavy snow with thunder": "src/assets/weather_webp_img/rain.webp",
} as { [key: string]: string };

export const imagesSvg = {
  arrow_up: "src/assets/arrow_up.svg",
  backIcons: "src/assets/back_icons.svg",
  eye: "src/assets/eye.svg",
  humidity: "src/assets/humidity.svg",
  options: "src/assets/icon_options.svg",
  search: "src/assets/icon_search.svg",
  sun: "src/assets/sun.svg",
  trash: "src/assets/trash.svg",
  uv_index: "src/assets/uv_index.svg",
  wind: "src/assets/wind.svg",
} as { [key: string]: string };
