export const imagesDay = {
  Sunny: "/assets/weather_svg_img/weather_clearDay.svg",
  Clear: "/assets/weather_svg_img/weather_clearDay.svg",
  "Partly cloudy": "/assets/weather_svg_img/weather_partlyCloudyDay.svg",
  Cloudy: "/assets/weather_svg_img/weather_cloudy.svg",
  Overcast: "/assets/weather_svg_img/weather_overcast.svg",
  Mist: "/assets/weather_svg_img/weather_mist.svg",
  "Patchy rain possible": "/assets/weather_svg_img/weather_patchyRainDay.svg",
  "Patchy snow possible": "/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Patchy sleet possible": "/assets/weather_svg_img/weather_patchySleetDay.svg",
  "Patchy freezing drizzle possible": "/assets/weather_svg_img/weather_fog.svg",
  "Thundery outbreaks possible": "/assets/weather_svg_img/weather_thunderyOutbreaksDay.svg",
  "Blowing snow": "/assets/weather_svg_img/weather_blizzard.svg",
  Blizzard: "/assets/weather_svg_img/weather_blizzard.svg",
  Fog: "/assets/weather_svg_img/weather_fog.svg",
  "Freezing fog": "/assets/weather_svg_img/weather_fog.svg",
  "Patchy light drizzle": "/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Light drizzle": "/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Freezing drizzle": "/assets/weather_svg_img/weather_fog.svg",
  "Heavy freezing drizzle": "/assets/weather_svg_img/weather_fog.svg",
  "Patchy light rain": "/assets/weather_svg_img/weather_lightRain.svg",
  "Light rain": "/assets/weather_svg_img/weather_lightRain.svg",
  "Moderate rain at times": "/assets/weather_svg_img/weather_moderateRainDay.svg",
  "Moderate rain": "/assets/weather_svg_img/weather_lightRain.svg",
  "Heavy rain at times": "/assets/weather_svg_img/weather_heavyRainDay.svg",
  "Heavy rain": "/assets/weather_svg_img/weather_heavyRain.svg",
  "Light freezing rain": "/assets/weather_svg_img/weather_fog.svg",
  "Moderate or heavy freezing rain": "/assets/weather_svg_img/weather_fog.svg",
  "Light sleet": "/assets/weather_svg_img/weather_lightSleet.svg",
  "Moderate or heavy sleet": "/assets/weather_svg_img/weather_lightSleet.svg",
  "Patchy light snow": "/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Light snow": "/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy moderate snow": "/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Moderate snow": "/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy heavy snow": "/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Heavy snow": "/assets/weather_svg_img/weather_heavySnow.svg",
  "Ice pellets": "/assets/weather_svg_img/weather_icePellets.svg",
  "Light rain shower": "/assets/weather_svg_img/weather_patchyRainDay.svg",
  "Moderate or heavy rain shower": "/assets/weather_svg_img/weather_moderateRainDay.svg",
  "Torrential rain shower": "/assets/weather_svg_img/weather_torrentialRainDay.svg",
  "Light sleet showers": "/assets/weather_svg_img/weather_patchySleetDay.svg",
  "Moderate or heavy sleet showers": "/assets/weather_svg_img/weather_moderateSleetDay.svg",
  "Light snow showers": "/assets/weather_svg_img/weather_patchySnowDay.svg",
  "Moderate or heavy snow showers": "/assets/weather_svg_img/weather_moderateSnowDay.svg",
  "Light showers of ice pellets": "/assets/weather_svg_img/weather_lightIcePelletsDay.svg",
  "Moderate or heavy showers of ice pellets": "/assets/weather_svg_img/weather_moderateIcePelletsDay.svg",
  "Patchy light rain with thunder": "/assets/weather_svg_img/weather_thunderyOutbreaksDay.svg",
  "Moderate or heavy rain with thunder": "/assets/weather_svg_img/weather_moderateThunder.svg",
  "Patchy light snow with thunder": "/assets/weather_svg_img/weather_patchyThunderSnowDay.svg",
  "Moderate or heavy snow with thunder": "/assets/weather_svg_img/weather_patchyThunderSnow.svg",
} as { [key: string]: string };

export const imagesNight = {
  Sunny: "/assets/weather_svg_img/weather_clearNight.svg",
  Clear: "/assets/weather_svg_img/weather_clearNight.svg",
  "Partly cloudy": "/assets/weather_svg_img/weather_partlyCloudyNight.svg",
  Cloudy: "/assets/weather_svg_img/weather_cloudy.svg",
  Overcast: "/assets/weather_svg_img/weather_overcast.svg",
  Mist: "/assets/weather_svg_img/weather_mist.svg",
  "Patchy rain possible": "/assets/weather_svg_img/weather_patchyRainNight.svg",
  "Patchy snow possible": "/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Patchy sleet possible": "/assets/weather_svg_img/weather_patchySleetNight.svg",
  "Patchy freezing drizzle possible": "/assets/weather_svg_img/weather_fog.svg",
  "Thundery outbreaks possible": "/assets/weather_svg_img/weather_thunderyOutbreaksNight.svg",
  "Blowing snow": "/assets/weather_svg_img/weather_blizzard.svg",
  Blizzard: "/assets/weather_svg_img/weather_blizzard.svg",
  Fog: "/assets/weather_svg_img/weather_fog.svg",
  "Freezing fog": "/assets/weather_svg_img/weather_fog.svg",
  "Patchy light drizzle": "/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Light drizzle": "/assets/weather_svg_img/weather_lightDrizzle.svg",
  "Freezing drizzle": "/assets/weather_svg_img/weather_fog.svg",
  "Heavy freezing drizzle": "/assets/weather_svg_img/weather_fog.svg",
  "Patchy light rain": "/assets/weather_svg_img/weather_lightRain.svg",
  "Light rain": "/assets/weather_svg_img/weather_lightRain.svg",
  "Moderate rain at times": "/assets/weather_svg_img/weather_moderateRainNight.svg",
  "Moderate rain": "/assets/weather_svg_img/weather_lightRain.svg",
  "Heavy rain at times": "/assets/weather_svg_img/weather_heavyRainNight.svg",
  "Heavy rain": "/assets/weather_svg_img/weather_heavyRain.svg",
  "Light freezing rain": "/assets/weather_svg_img/weather_fog.svg",
  "Moderate or heavy freezing rain": "/assets/weather_svg_img/weather_fog.svg",
  "Light sleet": "/assets/weather_svg_img/weather_lightSleet.svg",
  "Moderate or heavy sleet": "/assets/weather_svg_img/weather_lightSleet.svg",
  "Patchy light snow": "/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Light snow": "/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy moderate snow": "/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Moderate snow": "/assets/weather_svg_img/weather_lightSnow.svg",
  "Patchy heavy snow": "/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Heavy snow": "/assets/weather_svg_img/weather_heavySnow.svg",
  "Ice pellets": "/assets/weather_svg_img/weather_icePellets.svg",
  "Light rain shower": "/assets/weather_svg_img/weather_patchyRainNight.svg",
  "Moderate or heavy rain shower": "/assets/weather_svg_img/weather_moderateRainNight.svg",
  "Torrential rain shower": "/assets/weather_svg_img/weather_torrentialRainNight.svg",
  "Light sleet showers": "/assets/weather_svg_img/weather_patchySleetNight.svg",
  "Moderate or heavy sleet showers": "/assets/weather_svg_img/weather_moderateSleetNight.svg",
  "Light snow showers": "/assets/weather_svg_img/weather_patchySnowNight.svg",
  "Moderate or heavy snow showers": "/assets/weather_svg_img/weather_moderateSnowNight.svg",
  "Light showers of ice pellets": "/assets/weather_svg_img/weather_lightIcePelletsNight.svg",
  "Moderate or heavy showers of ice pellets": "/assets/weather_svg_img/weather_moderateIcePelletsNight.svg",
  "Patchy light rain with thunder": "/assets/weather_svg_img/weather_thunderyOutbreaksNight.svg",
  "Moderate or heavy rain with thunder": "/assets/weather_svg_img/weather_moderateThunder.svg",
  "Patchy light snow with thunder": "/assets/weather_svg_img/weather_patchyThunderSnowNight.svg",
  "Moderate or heavy snow with thunder": "/assets/weather_svg_img/weather_patchyThunderSnow.svg",
} as { [key: string]: string };

export const imagesBgDay = {
  Sunny: "/assets/weather_webp_img/clearDay.webp",
  Clear: "/assets/weather_webp_img/clearDay.webp",
  "Partly cloudy": "/assets/weather_webp_img/partlyCloudyDay.webp",
  Cloudy: "/assets/weather_webp_img/cloudy.webp",
  Overcast: "/assets/weather_webp_img/overcast.webp",
  Mist: "/assets/weather_webp_img/mist.webp",
  "Patchy rain possible": "/assets/weather_webp_img/cloudy.webp",
  "Patchy snow possible": "/assets/weather_webp_img/cloudy.webp",
  "Patchy sleet possible": "/assets/weather_webp_img/cloudy.webp",
  "Patchy freezing drizzle possible": "/assets/weather_webp_img/mist.webp",
  "Thundery outbreaks possible": "/assets/weather_webp_img/overcast.webp",
  "Blowing snow": "/assets/weather_webp_img/overcast.webp",
  Blizzard: "/assets/weather_webp_img/overcast.webp",
  Fog: "/assets/weather_webp_img/mist.webp",
  "Freezing fog": "/assets/weather_webp_img/mist.webp",
  "Patchy light drizzle": "/assets/weather_webp_img/rain.webp",
  "Light drizzle": "/assets/weather_webp_img/rain.webp",
  "Freezing drizzle": "/assets/weather_webp_img/mist.webp",
  "Heavy freezing drizzle": "/assets/weather_webp_img/mist.webp",
  "Patchy light rain": "/assets/weather_webp_img/rain.webp",
  "Light rain": "/assets/weather_webp_img/rain.webp",
  "Moderate rain at times": "/assets/weather_webp_img/rain.webp",
  "Moderate rain": "/assets/weather_webp_img/rain.webp",
  "Heavy rain at times": "/assets/weather_webp_img/rain.webp",
  "Heavy rain": "/assets/weather_webp_img/rain.webp",
  "Light freezing rain": "/assets/weather_webp_img/mist.webp",
  "Moderate or heavy freezing rain": "/assets/weather_webp_img/mist.webp",
  "Light sleet": "/assets/weather_webp_img/rain.webp",
  "Moderate or heavy sleet": "/assets/weather_webp_img/rain.webp",
  "Patchy light snow": "/assets/weather_webp_img/cloudy.webp",
  "Light snow": "/assets/weather_webp_img/cloudy.webp",
  "Patchy moderate snow": "/assets/weather_webp_img/cloudy.webp",
  "Moderate snow": "/assets/weather_webp_img/cloudy.webp",
  "Patchy heavy snow": "/assets/weather_webp_img/cloudy.webp",
  "Heavy snow": "/assets/weather_webp_img/cloudy.webp",
  "Ice pellets": "/assets/weather_webp_img/cloudy.webp",
  "Light rain shower": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy rain shower": "/assets/weather_webp_img/rain.webp",
  "Torrential rain shower": "/assets/weather_webp_img/rain.webp",
  "Light sleet showers": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy sleet showers": "/assets/weather_webp_img/rain.webp",
  "Light snow showers": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy snow showers": "/assets/weather_webp_img/cloudy.webp",
  "Light showers of ice pellets": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy showers of ice pellets": "/assets/weather_webp_img/cloudy.webp",
  "Patchy light rain with thunder": "/assets/weather_webp_img/rain.webp",
  "Moderate or heavy rain with thunder": "/assets/weather_webp_img/rain.webp",
  "Patchy light snow with thunder": "/assets/weather_webp_img/rain.webp",
  "Moderate or heavy snow with thunder": "/assets/weather_webp_img/rain.webp",
} as { [key: string]: string };

export const imagesBgNight = {
  Sunny: "/assets/weather_webp_img/clearNight.webp",
  Clear: "/assets/weather_webp_img/clearNight.webp",
  "Partly cloudy": "/assets/weather_webp_img/partlyCloudyNight.webp",
  Cloudy: "/assets/weather_webp_img/cloudy.webp",
  Overcast: "/assets/weather_webp_img/overcast.webp",
  Mist: "/assets/weather_webp_img/mist.webp",
  "Patchy rain possible": "/assets/weather_webp_img/cloudy.webp",
  "Patchy snow possible": "/assets/weather_webp_img/cloudy.webp",
  "Patchy sleet possible": "/assets/weather_webp_img/cloudy.webp",
  "Patchy freezing drizzle possible": "/assets/weather_webp_img/mist.webp",
  "Thundery outbreaks possible": "/assets/weather_webp_img/overcast.webp",
  "Blowing snow": "/assets/weather_webp_img/overcast.webp",
  Blizzard: "/assets/weather_webp_img/overcast.webp",
  Fog: "/assets/weather_webp_img/mist.webp",
  "Freezing fog": "/assets/weather_webp_img/mist.webp",
  "Patchy light drizzle": "/assets/weather_webp_img/rain.webp",
  "Light drizzle": "/assets/weather_webp_img/rain.webp",
  "Freezing drizzle": "/assets/weather_webp_img/mist.webp",
  "Heavy freezing drizzle": "/assets/weather_webp_img/mist.webp",
  "Patchy light rain": "/assets/weather_webp_img/rain.webp",
  "Light rain": "/assets/weather_webp_img/rain.webp",
  "Moderate rain at times": "/assets/weather_webp_img/rain.webp",
  "Moderate rain": "/assets/weather_webp_img/rain.webp",
  "Heavy rain at times": "/assets/weather_webp_img/rain.webp",
  "Heavy rain": "/assets/weather_webp_img/rain.webp",
  "Light freezing rain": "/assets/weather_webp_img/mist.webp",
  "Moderate or heavy freezing rain": "/assets/weather_webp_img/mist.webp",
  "Light sleet": "/assets/weather_webp_img/rain.webp",
  "Moderate or heavy sleet": "/assets/weather_webp_img/rain.webp",
  "Patchy light snow": "/assets/weather_webp_img/cloudy.webp",
  "Light snow": "/assets/weather_webp_img/cloudy.webp",
  "Patchy moderate snow": "/assets/weather_webp_img/cloudy.webp",
  "Moderate snow": "/assets/weather_webp_img/cloudy.webp",
  "Patchy heavy snow": "/assets/weather_webp_img/cloudy.webp",
  "Heavy snow": "/assets/weather_webp_img/cloudy.webp",
  "Ice pellets": "/assets/weather_webp_img/cloudy.webp",
  "Light rain shower": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy rain shower": "/assets/weather_webp_img/rain.webp",
  "Torrential rain shower": "/assets/weather_webp_img/rain.webp",
  "Light sleet showers": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy sleet showers": "/assets/weather_webp_img/rain.webp",
  "Light snow showers": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy snow showers": "/assets/weather_webp_img/cloudy.webp",
  "Light showers of ice pellets": "/assets/weather_webp_img/cloudy.webp",
  "Moderate or heavy showers of ice pellets": "/assets/weather_webp_img/cloudy.webp",
  "Patchy light rain with thunder": "/assets/weather_webp_img/rain.webp",
  "Moderate or heavy rain with thunder": "/assets/weather_webp_img/rain.webp",
  "Patchy light snow with thunder": "/assets/weather_webp_img/rain.webp",
  "Moderate or heavy snow with thunder": "/assets/weather_webp_img/rain.webp",
} as { [key: string]: string };

export const imagesSvg = {
  arrow_up: "/assets/arrow_up.svg",
  backIcons: "/assets/back_icons.svg",
  visibility: "/assets/icons/visibility.svg",
  humidity: "/assets/icons/humidity.svg",
  search: "/assets/icon_search.svg",
  sun: "/assets/sun.svg",
  sunrise: "/assets/icons/sunrise.svg",
  trash: "/assets/icons/trash.svg",
  uv_index: "/assets/icons/uv_index.svg",
  wind: "/assets/icons/wind.svg",
} as { [key: string]: string };
